baseURL = "http://example.org/"
languageCode = "zh-CN"
title = "AMZsellerkit"
theme = "hugo-webstack"

#true:允许大写字母url路径，false:将url路径转换成小写
disablePathToLower = true

#页脚：作者名字
copyright = "Angelica"

#网站信息，不显示，仅供搜索引擎参考
[params]
  keywords = "amazon,amazon seller,seller tool"
  description = "amazon seller hub,seller tools"

#是否开启搜索栏，true开启，false关闭
[params.search]
  enable = false

#设置默认模式，true暗色模式，false亮色模式
[params.darkmode]
  enable = false

#主页菜单栏显示在线编辑按钮（编辑github文件，适用于自动化部署的情况）
[params.edit]
  # true显示按钮，false不显示
  enable = false
  # github文件的远程链接，改成自己的
  url = "https://github.com/Angelica818/nav/blob/main/data/webstack.yml"
  
#桌面端右上角code按钮
[params.github]
  enable = false #true显示 false隐藏
  url = "https://github.com/Angelica818/nav/"
  
[permalinks]  
  404 = "/404.html"

#是否对本地搜索功能开启拼音匹配，true开启，false禁止。
#拼音库体积337k，支持首字母匹配
[params.pinyin]
  enable = false

  <!-- Google tag (gtag.js) -->
<script async src="https://www.googletagmanager.com/gtag/js?id=G-7N4PKM2GK8"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'G-7N4PKM2GK8');
</script>
